### PR TITLE
Utilize interfaces to define functionality (allows for runtime edits).

### PR DESCRIPTION
**Pull request by jaridmargolin**

### CODE REVIEW

**Comment by Jaymon** [comment]
on a superficial level this looks good, can you give me a quick snippet of code on how the interface is supposed to work? I can help more with naming and implementation details after seeing how it will be used.

**Comment by jaridmargolin** [comment]
Well this is first pass for the inner mechanics. As a second pass I'm thinking I could add a static method for setting interfaces:

So in a project you could use a modified interface like so:
```
WDE.Field.setInterface('field', new MyModifiedFiledInterace())
```

The advantage being, now all upstream Field subclasses will utilize this modified interface.

---

Also allows me to create multi purpose components. For example I could give a custom component both the `list` and `form` interfaces:
```
class CustomForm extends WDE.El {

  static get implements () {
    return _.extend({}, super.implements, {
      'form': new FormInterface(),
      'list': new ListInterface()
    })
  }

}
```

**Comment by jaridmargolin** [comment]
Hmmm looking at this and wondering why interfaces are defined inside of a prop `implements`. Would make more sense just to have the prop be `interfaces`? Not sure why this indirection exists?

Also, should provide a utility method for extending interfaces from super, as this is currently the most common use case.

**Comment by jaridmargolin** [comment]
I could maybe also auto discover interfaces based on naming conventions...

Similar to what was done with primitives, at instantiation of WDE, I can load the interfaces directory. Then when instantiating a ElClass, it looks for corresponding interface?

**Comment by jaridmargolin** [comment]
I hate throwing away work, but I think the added complexity is not worth the little flexibility it gives.

**Pull request closed without merging**
